package com.patan.app.models;

public enum Breed {
    POODLE, CHIHUAHUA, PUG, BULDOG_FRANCES, BULLDOG, YORKSHIRE, BICHON_MALTES, SHIHTZU, TERRANOVA, LABRADOR, HUSKY, POMERANIA, BOXER, LEBREL, SAMOYEDO, BEAGLE, CORGI, TECKEL, STREET
}